name: Create docs

on:
  workflow_dispatch:

jobs:
    - name: Checkout docs repo
      uses: actions/checkout@v3
      with:
        path: 'dist'

    # Clone Noahh repo
    - name: Checkout Noahh repo
      uses: actions/checkout@v3
      with:
        repository: 'noahh-sdk/noahh'
        path: 'noahh'
  
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working_directory: 'noahh/loader/include/Noahh'
        doxyfile-path: 'dist/Doxyfile'

    - name: Setup Pages
      uses: actions/configure-pages@v2
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'
      
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1